name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'  # 当推送以v开头的标签时触发构建
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --name="PDF转图片工具" ^
                   --windowed ^
                   --onefile ^
                   --icon=assets/icon.ico ^
                   --add-data="src;src" ^
                   src/main.py
                   
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF-to-Image-Tool-Windows
        path: dist/PDF转图片工具.exe